version: '3.8'

services: 
    mysqldb:
      image: mysql:5.7
      restart: unless-stopped
      env_file: ./.env
      environment:
        - MYSQL_DATABASE=$DB_NAME
        - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      volumes:
        - db:/var/lib/mysql
        - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10
    app:
      depends_on:
        mysqldb:
          condition: service_healthy
      build: .
      restart: unless-stopped
      env_file: ./.env
      ports:
        - 3000:3000
      environment:
        - DB_HOST=mysqldb
        - DB_USER=$DB_USER
        - DB_PASSWORD=$DB_PASSWORD
        - DB_NAME=$DB_NAME
      stdin_open: true
      tty: true

volumes:
  db: